### PR TITLE
HTML Processing Fixes

### PR DESCRIPTION
**Pull request by newsch**
- [ ] Add tests for each case

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
Thanks! LGTM

**Comment by newsch** [comment]
Not yet, I'm trying to find some sample articles for tests.

**Comment by biodranik** [comment]
Should it be rebased?

**Comment by newsch** [comment]
From my tests the wrapper div handling was roughly a wash. Some data-heavy articles use them for custom lists and tables which greatly increase the size for little value. I've removed it for now until I can find better heuristics for it.

**Comment by biodranik** [comment]
Thanks! It's better to avoid storing large chunks of data, most people won't read them anyway from a mobile device on the go.

**Pull request merged**
