### PR TITLE
Debugging Improvements

### PR DESCRIPTION
**Pull request by newsch**
- Add check-html command to bulk-analyze html files
- Add option to write matched, erroring, or panicing json to stdout
- [x] decide on parseable structured logging format, json or logfmt?

### CODE REVIEW

**Review by biodranik — APPROVED** [review]
LGTM

**Comment by newsch** [comment]
@biodranik do you care what format the logs are in?
Something like [logfmt](https://brandur.org/logfmt) would be more readable than JSON but also more parseable for when I'm analyzing the logs than `tracing`'s default. That way we can keep it simple without having multiple levels/formats/outputs or detection logic.

**Comment by biodranik** [comment]
I'm ok to try it )

**Comment by biodranik** [comment]
@newsch should these changes be merged?

**Comment by newsch** [comment]
@biodranik no need to rerun in production with this yet.

**Pull request merged**
